[www]
user = www-data
group = www-data

; Listen on all interfaces so Nginx container can connect
listen = 0.0.0.0:9000

; Process manager settings
pm = dynamic
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 35

; Performance
pm.max_requests = 500

; Timeouts
request_terminate_timeout = 120s

; Access log
access.log = /proc/self/fd/2

; Catch worker output
catch_workers_output = yes
decorate_workers_output = no

; Clear environment
clear_env = no
